networks:
  hotmart_net:
    driver: bridge

services:
  chroma_db:
    image: chromadb/chroma
    ports:
      - $CHROMA_PORT:8000
    container_name: chroma-db
    # Removing authentification for now just to make it easy for other people to run the code
    # environment: 
    # CHROMA_SERVER_AUTHN_CREDENTIALS: $CHROMA_SERVER_AUTHN_CREDENTIALS
    # CHROMA_SERVER_AUTHN_PROVIDER: $CHROMA_SERVER_AUTHN_PROVIDER
    healthcheck:
      test: "curl http://localhost:8000 || exit 1"
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - hotmart_net

  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ./hotmart_rag_llm/data/ollama/:/root/.ollama
      - ./hotmart_rag_llm/entrypoint.sh:/entrypoint.sh
    container_name: ollama-hotmart-rag
    tty: true
    restart: always
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]
    healthcheck:
      test: "ollama --version && ollama ps || exit 1"
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    networks:
      - hotmart_net
    # comment this block to use CPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  hotmart_rag_db:
    build: ./hotmart_rag_db/
    container_name: hotmart-rag-db
    ports:
      - $FASTAPI_PORT:$FASTAPI_PORT
    environment:
      FASTAPI_HOST: 0.0.0.0
      FASTAPI_PORT: $FASTAPI_PORT
      CHROMA_HOST: chroma_db
      CHROMA_PORT: 8000
      CHROMA_CLIENT_AUTH_CREDENTIALS: $CHROMA_CLIENT_AUTH_CREDENTIALS
      CHROMA_COLLECTION_NAME: $CHROMA_COLLECTION_NAME
      CHROMA_EMBEDDING_MODEL: $CHROMA_EMBEDDING_MODEL
    depends_on:
      chroma_db:
        condition: service_healthy

    healthcheck:
      test: curl --fail http://localhost:8091/healthcheck || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - hotmart_net

  hotmart_rag_llm:
    build: ./hotmart_rag_llm/
    container_name: hotmart-rag-llm
    ports:
      - $RAG_LLM_FASTAPI_PORT:8093
    environment:
      RAG_LLM_FASTAPI_PORT: $RAG_LLM_FASTAPI_PORT
      RAG_LLM_FASTAPI_HOST: 0.0.0.0
      LLM_BASE_URL: $LLM_BASE_URL
      DB_API_HOST: $DB_API_HOST
      DB_API_PORT: $FASTAPI_PORT
      SYSTEM_MESSAGE: $SYSTEM_MESSAGE
      TEMPERATURE: $TEMPERATURE
      SEED: $SEED
      MAX_TOKENS: $MAX_TOKENS
    depends_on:
      ollama:
        condition: service_healthy
      hotmart_rag_db:
        condition: service_healthy
    # comment this block to use CPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    networks:
      - hotmart_net
